# docker-compose.yml
version: '3'
services:
  airflow-webserver:
    image: apache/airflow:2.10.0
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
  airflow-scheduler:
    image: apache/airflow:2.10.0
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
  airflow-init:
    image: apache/airflow:2.10.0
    entrypoint: airflow db init
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
